run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  tests: true

output:
  print-issued-lines: false
  print-linter-name: true
  uniq-by-line: false
  sort-results: true

linters:
  disable-all: true

  # Full linter list: https://golangci-lint.run/usage/linters
  enable:
    - errcheck
    - goimports
    #- revive
    - govet
    - staticcheck
    - unused
    - testifylint
    #- gosec
    #- dupl
    #- goconst
    #- gofmt
    #- tagliatelle

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  revive:
    # Only these rules are enabled.
    rules:
      - name: exported
        arguments:
        - disableStutteringCheck

  #staticcheck:
  #  checks:
  #    - "all"
  #errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    # Such cases aren't reported by default.
    # Default: false
  #  check-type-assertions: false
  #dupl:
    # Tokens count to trigger issue, Default: 150
  #  threshold: 100