version: "3"
services:

  # MQTT 
  mqtt:
    image: eclipse-mosquitto
    hostname: mqtt
    container_name: mqtt
    expose:
      - "10003"
    ports:
      - "10003:10003"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mosquitto/data
      - /mosquitto/log
    healthcheck:
      test: [ "CMD-SHELL", "timeout -t 5 mosquitto_sub -t '$$SYS/#' -C 1 | grep -v Error || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 6

      
  # cluster-level mongoDB
  mongo_cluster:
    image: mongo:3.6
    container_name: mongo
    hostname: mongo
    ports:
      - "10007:10007"
    volumes:
      - 'mongodb_data:/mongodb'
    command: mongod --port 10007

# cluster-level mongoDB
  mongo_clusternet:
    image: mongo:3.6
    container_name: cluster_mongo_net
    hostname: cluster_mongo_net
    ports:
      - "10207:10207"
    volumes:
      - 'mongodb_net_data:/mongodb'
    command: mongod --port 10207


# Cluster Manager
  cluster_service_manager:
    image: ghcr.io/edgeio/edgeionet/cluster-service-manager:v0.01-experimental
    container_name: cluster_service_manager
    hostname: cluster_service_manager
    expose:
      - "10200"
    ports:
      - "10200:10200"
    environment:
      - MY_PORT=10200
      - MQTT_BROKER_PORT=10003
      - MQTT_BROKER_URL=mqtt
      - ROOT_SERVICE_MANAGER_URL=${SYSTEM_MANAGER_URL}
      - ROOT_SERVICE_MANAGER_PORT=10100
      - SYSTEM_MANAGER_URL=cluster_manager
      - SYSTEM_MANAGER_PORT=10000
      - CLUSTER_MONGO_URL=cluster_mongo_net
      - CLUSTER_MONGO_PORT=10207
    depends_on:
      - mongo_clusternet
      - mqtt

# Cluster Manager
  cluster_manager:
    image: cluster_manager
    build: cluster-manager/
    container_name: cluster_manager
    hostname: cluster_manager
    expose:
      - "10000"
      - "10001"
    ports:
      - "10000:10000"
      - "10001:10001"
    environment:
      - MY_PORT=10000
      - SYSTEM_MANAGER_URL=${SYSTEM_MANAGER_URL}
      - CLUSTER_SERVICE_MANAGER_ADDR=cluster_service_manager
      - CLUSTER_SERVICE_MANAGER_PORT=10200
      - SYSTEM_MANAGER_PORT=10000
      - CLUSTER_MONGO_URL=mongo
      - CLUSTER_MONGO_PORT=10007
      - CLUSTER_SCHEDULER_URL=cluster_scheduler
      - CLUSTER_SCHEDULER_PORT=10005
      - MQTT_BROKER_URL=mqtt
      - MQTT_BROKER_PORT=10003
      - CLUSTER_NAME=${CLUSTER_NAME}
      - CLUSTER_LOCATION=${CLUSTER_LOCATION}
      - CLUSTER_PUBLIC_IP=${CLUSTER_PUBLIC_IP}
      - CLUSTER_PRIVATE_IP=${CLUSTER_PRIVATE_IP}
    depends_on:
      - mongo_cluster
      - mqtt
      - cluster_scheduler
      - cluster_service_manager


  # Cluster Scheduler
  cluster_scheduler:
    image: cluster_scheduler
    build: cluster-scheduler/
    container_name: cluster_scheduler
    hostname: cluster_scheduler
    expose:
      - "10005"
    ports:
      - "10005:10005"
    environment:
      - MY_PORT=10005
      - CLUSTER_MANAGER_URL=cluster_manager
      - CLUSTER_MANAGER_PORT=10000
      - CLUSTER_MONGO_URL=mongo
      - CLUSTER_MONGO_PORT=10007
      - REDIS_ADDR=redis://:clusterRedis@redis:6379
    depends_on:
      - redis
      - mongo_cluster


  # Redis for the Cluster Scheduler as Job Queue
  redis:
    image: redis
    hostname: redis
    container_name: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    command: redis-server --requirepass clusterRedis


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - 10009:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - cluster_manager


volumes:
  mongodb_data:
    driver: local
  mongodb_net_data:
    driver: local
