name: Testbed Oneshot - Multiple Scenarios Test Deployment

on:
  pull_request_review:
    types: [submitted]

jobs:
  deploy:
    name: Testbed Oneshot Execution
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./.github/actions/testbed-deploy

      - name: Trigger Testbed Oneshot Execution
        uses: ./.github/actions/testbed-deploy
        with:
          AWX_URL: ${{ secrets.TOWER_HOST }}
          AWX_TOKEN: ${{ secrets.TOWER_TOKEN }}
          AWX_TEMPLATE_ID: ${{ secrets.ONESHOT_TEMPLATE_ID }}
          PR_BRANCH: ${{ github.event.pull_request.head.ref }}
          PR_USER: ${{ github.event.pull_request.head.user.login }}
          PR_COMMIT: ${{ github.event.pull_request.head.sha }}
